name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Code auschecken
        uses: actions/checkout@v3

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Abhängigkeiten installieren
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: PyInstaller ausführen
        run: |
          pyinstaller --onefile --name openimmo main.py

      - name: EXE als Artifact speichern
        uses: actions/upload-artifact@v4
        with:
          name: openimmo-exe
          path: dist/openimmo.exe